sudo: required
dist: bionic

language: bash

cache:
  apt: true
  directories:
  - /usr/local/src

before_install:
  - rm -rf ~/.gnupg

git:
  quiet: true

env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
  - sudo apt-get -qq autoremove --purge
addons:
  apt:
    update: true

script:
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -y --force-yes curl wget ccze
  - sudo bash nginx-build.sh --travis
  - sudo bash nginx-build.sh --travis --stable
  - sudo bash nginx-build.sh --travis --full
  - sudo bash nginx-build.sh --travis --pagespeed-beta
  - sudo bash nginx-build.sh --travis --libressl
  - sudo bash nginx-build.sh --travis --pagespeed-beta
  - sudo ls -alh /usr/sbin/nginx
  - sudo chown -R travis /usr/local/src
  - sudo chmod 755 /usr/local/src
