language: bash

dist: xenial

branches:
  only:
  - develop

cache:
  directories:
  - /usr/local/src

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo apt-get -qq autoremove --purge
  - sudo apt-get update -qq

script:
  - lsb_release -a
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -y --force-yes git nginx curl wget ccze
  - sudo bash nginx-build.sh && sudo bash nginx-build.sh --stable && sudo bash nginx-build.sh --full || sudo bash -c 'tail -n 100 /tmp/nginx-ee.log | ccze -A'
  - sudo chown -R travis /usr/local/src
  - sudo chmod 755 /usr/local/src