sudo: required
dist: xenial

language: bash

cache:
  apt: true
  directories:
  - /usr/local/src

before_install:
  - rm -rf ~/.gnupg

git:
  quiet: true

before_script:
  - sudo apt-get -qq autoremove --purge
addons:
  apt:
    update: true

script:
  - lsb_release -a
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -y --force-yes nginx curl wget ccze
  - sudo bash nginx-build.sh --stable --travis && sudo bash nginx-build.sh --travis && sudo bash nginx-build.sh --full --travis || sudo bash -c 'tail -n 100 /tmp/nginx-ee.log | ccze -A'
  - sudo ls -alh /usr/sbin/nginx
  - sudo chown -R travis /usr/local/src
  - sudo chmod 755 /usr/local/src
