name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Prepare VM
      run: |
        sudo apt update -qq
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt update -qq
        sudo apt install libgd-dev -y        
    - name: Mainline build
      run: sudo bash nginx-build.sh
    - name: Stable build
      run: sudo bash nginx-build.sh --stable
    - name: Full build
      run: sudo bash nginx-build.sh --full
    - name: libressl build
      run: sudo bash nginx-build.sh --libressl
    - name: pagespeed beta build
      run: sudo bash nginx-build.sh --pagespeed-beta
    - name: openssl-dev build
      run: sudo bash nginx-build.sh --openssl-dev
    - name: dynamic build
      run: sudo bash nginx-build.sh --dynamic
      
