name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Mainline build
      run: sudo bash nginx-build.sh
    - name: Stable build
      run: sudo bash nginx-build.sh --stable
    - name: Full build
      run: sudo bash nginx-build.sh --full
    - name: libressl build
      run: sudo bash nginx-build.sh --libressl
    - name: pagespeed beta build
      run: sudo bash nginx-build.sh --pagespeed-beta
    - name: openssl-dev build
      run: sudo bash nginx-build.sh --openssl-dev
    - name: dynamic build
      run: sudo bash nginx-build.sh --dynamic
      
